### Instruções

* Rode o código da célula abaixo para obter os textos que serão usados no desafio, utilize entre 10 a 20 textos da base mudando o N.
* Crie um DataFrame com o TF, IDF e TF-IDF de todos os termos
* O que os 5 termos com o maior TF-IDF significam na tua opinião? Porque eles são os maiores?
**Não esqueça dos passos antes de ter um termo/token**

In [13]:
import pandas as pd
import numpy as np
from sklearn.datasets import fetch_20newsgroups
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfTransformer

In [14]:
# Descomente a linha de baixo se quiser ver mais detalhes do dataset
print(fetch_20newsgroups.__doc__)

Load the filenames and data from the 20 newsgroups dataset (classification).

    Download it if necessary.

    =================   ==========
    Classes                     20
    Samples total            18846
    Dimensionality               1
    Features                  text
    =================   ==========

    Read more in the :ref:`User Guide <20newsgroups_dataset>`.

    Parameters
    ----------
    data_home : str or path-like, default=None
        Specify a download and cache folder for the datasets. If None,
        all scikit-learn data is stored in '~/scikit_learn_data' subfolders.

    subset : {'train', 'test', 'all'}, default='train'
        Select the dataset to load: 'train' for the training set, 'test'
        for the test set, 'all' for both, with shuffled ordering.

    categories : array-like, dtype=str, default=None
        If None (default), load all the categories.
        If not None, list of category names to load (other categories
        ignored).

    shuffle : bool, default=True
        Whether or not to shuffle the data: might be important for models that
        make the assumption that the samples are independent and identically
        distributed (i.i.d.), such as stochastic gradient descent.

    random_state : int, RandomState instance or None, default=42
        Determines random number generation for dataset shuffling. Pass an int
        for reproducible output across multiple function calls.
        See :term:`Glossary <random_state>`.

    remove : tuple, default=()
        May contain any subset of ('headers', 'footers', 'quotes'). Each of
        these are kinds of text that will be detected and removed from the
        newsgroup posts, preventing classifiers from overfitting on
        metadata.

        'headers' removes newsgroup headers, 'footers' removes blocks at the
        ends of posts that look like signatures, and 'quotes' removes lines
        that appear to be quoting another post.

        'headers' follows an exact standard; the other filters are not always
        correct.

    download_if_missing : bool, default=True
        If False, raise an OSError if the data is not locally available
        instead of trying to download the data from the source site.

    return_X_y : bool, default=False
        If True, returns `(data.data, data.target)` instead of a Bunch
        object.

        .. versionadded:: 0.22

    n_retries : int, default=3
        Number of retries when HTTP errors are encountered.

        .. versionadded:: 1.5

    delay : float, default=1.0
        Number of seconds between retries.

        .. versionadded:: 1.5

    Returns
    -------
    bunch : :class:`~sklearn.utils.Bunch`
        Dictionary-like object, with the following attributes.

        data : list of shape (n_samples,)
            The data list to learn.
        target: ndarray of shape (n_samples,)
            The target labels.
        filenames: list of shape (n_samples,)
            The path to the location of the data.
        DESCR: str
            The full description of the dataset.
        target_names: list of shape (n_classes,)
            The names of target classes.

    (data, target) : tuple if `return_X_y=True`
        A tuple of two ndarrays. The first contains a 2D array of shape
        (n_samples, n_classes) with each row representing one sample and each
        column representing the features. The second array of shape
        (n_samples,) contains the target samples.

        .. versionadded:: 0.22

    Examples
    --------
    >>> from sklearn.datasets import fetch_20newsgroups
    >>> cats = ['alt.atheism', 'sci.space']
    >>> newsgroups_train = fetch_20newsgroups(subset='train', categories=cats)
    >>> list(newsgroups_train.target_names)
    ['alt.atheism', 'sci.space']
    >>> newsgroups_train.filenames.shape
    (1073,)
    >>> newsgroups_train.target.shape
    (1073,)
    >>> newsgroups_train.target[:10]
    array([0, 1, 1, 1, 0, 1, 1, 0, 0, 0])

In [15]:
# selecionando a quantidade de textos que serão utilizados no desafio
N = 15
raw_documents= fetch_20newsgroups(subset='train', return_X_y=True)[0]

corpus = []

for idx, doc in enumerate(raw_documents[:N]):
  print(f"========== Doc {idx} ==========")
  print(doc)
  corpus.append(doc)

========== Doc 0 ==========
From: lerxst@wam.umd.edu (where's my thing)
Subject: WHAT car is this!?
Nntp-Posting-Host: rac3.wam.umd.edu
Organization: University of Maryland, College Park
Lines: 15

 I was wondering if anyone out there could enlighten me on this car I saw
the other day. It was a 2-door sports car, looked to be from the late 60s/
early 70s. It was called a Bricklin. The doors were really small. In addition,
the front bumper was separate from the rest of the body. This is
all I know. If anyone can tellme a model name, engine specs, years
of production, where this car is made, history, or whatever info you
have on this funky looking car, please e-mail.

Thanks,
- IL
   ---- brought to you by your neighborhood Lerxst ----





========== Doc 1 ==========
From: guykuo@carson.u.washington.edu (Guy Kuo)
Subject: SI Clock Poll - Final Call
Summary: Final call for SI clock reports
Keywords: SI,acceleration,clock,upgrade
Article-I.D.: shelley.1qvfo9INNc3s
Organization: University of Washington
Lines: 11
NNTP-Posting-Host: carson.u.washington.edu

A fair number of brave souls who upgraded their SI clock oscillator have
shared their experiences for this poll. Please send a brief message detailing
your experiences with the procedure. Top speed attained, CPU rated speed,
add on cards and adapters, heat sinks, hour of usage per day, floppy disk
functionality with 800 and 1.4 m floppies are especially requested.

I will be summarizing in the next two days, so please add to the network
knowledge base if you have done the clock upgrade and haven't answered this
poll. Thanks.

Guy Kuo <guykuo@u.washington.edu>

========== Doc 2 ==========
From: twillis@ec.ecn.purdue.edu (Thomas E Willis)
Subject: PB questions...
Organization: Purdue University Engineering Computer Network
Distribution: usa
Lines: 36

well folks, my mac plus finally gave up the ghost this weekend after
starting life as a 512k way back in 1985.  sooo, i'm in the market for a
new machine a bit sooner than i intended to be...

i'm looking into picking up a powerbook 160 or maybe 180 and have a bunch
of questions that (hopefully) somebody can answer:

* does anybody know any dirt on when the next round of powerbook
introductions are expected?  i'd heard the 185c was supposed to make an
appearence "this summer" but haven't heard anymore on it - and since i
don't have access to macleak, i was wondering if anybody out there had
more info...

* has anybody heard rumors about price drops to the powerbook line like the
ones the duo's just went through recently?

* what's the impression of the display on the 180?  i could probably swing
a 180 if i got the 80Mb disk rather than the 120, but i don't really have
a feel for how much "better" the display is (yea, it looks great in the
store, but is that all "wow" or is it really that good?).  could i solicit
some opinions of people who use the 160 and 180 day-to-day on if its worth
taking the disk size and money hit to get the active display?  (i realize
this is a real subjective question, but i've only played around with the
machines in a computer store breifly and figured the opinions of somebody
who actually uses the machine daily might prove helpful).

* how well does hellcats perform?  ;)

thanks a bunch in advance for any info - if you could email, i'll post a
summary (news reading time is at a premium with finals just around the
corner... :( )
--
Tom Willis  \  twillis@ecn.purdue.edu    \    Purdue Electrical Engineering
---------------------------------------------------------------------------
"Convictions are more dangerous enemies of truth than lies."  - F. W.
Nietzsche

========== Doc 3 ==========
From: jgreen@amber (Joe Green)
Subject: Re: Weitek P9000 ?
Organization: Harris Computer Systems Division
Lines: 14
Distribution: world
NNTP-Posting-Host: amber.ssd.csd.harris.com
X-Newsreader: TIN [version 1.1 PL9]

Robert J.C. Kyanko (rob@rjck.UUCP) wrote:
> abraxis@iastate.edu writes in article <abraxis.734340159@class1.iastate.edu>:
> > Anyone know about the Weitek P9000 graphics chip?
> As far as the low-level stuff goes, it looks pretty nice.  It's got this
> quadrilateral fill command that requires just the four points.

Do you have Weitek's address/phone number?  I'd like to get some information
about this chip.

--
Joe Green				Harris Corporation
jgreen@csd.harris.com			Computer Systems Division
"The only thing that really scares me is a person with no sense of humor."
						-- Jonathan Winters

========== Doc 4 ==========
From: jcm@head-cfa.harvard.edu (Jonathan McDowell)
Subject: Re: Shuttle Launch Question
Organization: Smithsonian Astrophysical Observatory, Cambridge, MA,  USA
Distribution: sci
Lines: 23

From article <C5owCB.n3p@world.std.com>, by tombaker@world.std.com (Tom A Baker):
>>In article <C5JLwx.4H9.1@cs.cmu.edu>, ETRAT@ttacs1.ttu.edu (Pack Rat) writes...
>>>"Clear caution & warning memory.  Verify no unexpected
>>>errors. ...".  I am wondering what an "expected error" might
>>>be.  Sorry if this is a really dumb question, but
>
> Parity errors in memory or previously known conditions that were waivered.
>    "Yes that is an error, but we already knew about it"
> I'd be curious as to what the real meaning of the quote is.
>
> tom


My understanding is that the 'expected errors' are basically
known bugs in the warning system software - things are checked
that don't have the right values in yet because they aren't
set till after launch, and suchlike. Rather than fix the code
and possibly introduce new bugs, they just tell the crew
'ok, if you see a warning no. 213 before liftoff, ignore it'.

 - Jonathan



========== Doc 5 ==========
From: dfo@vttoulu.tko.vtt.fi (Foxvog Douglas)
Subject: Re: Rewording the Second Amendment (ideas)
Organization: VTT
Lines: 58

In article <1r1eu1$4t@transfer.stratus.com> cdt@sw.stratus.com (C. D. Tavares) writes:
>In article <1993Apr20.083057.16899@ousrvr.oulu.fi>, dfo@vttoulu.tko.vtt.fi (Foxvog Douglas) writes:
>> In article <1qv87v$4j3@transfer.stratus.com> cdt@sw.stratus.com (C. D. Tavares) writes:
>> >In article <C5n3GI.F8F@ulowell.ulowell.edu>, jrutledg@cs.ulowell.edu (John Lawrence Rutledge) writes:
>
>> >> The massive destructive power of many modern weapons, makes the
>> >> cost of an accidental or crimial usage of these weapons to great.
>> >> The weapons of mass destruction need to be in the control of
>> >> the government only.  Individual access would result in the
>> >> needless deaths of millions.  This makes the right of the people
>> >> to keep and bear many modern weapons non-existant.

>> >Thanks for stating where you're coming from.  Needless to say, I
>> >disagree on every count.

>> You believe that individuals should have the right to own weapons of
>> mass destruction?  I find it hard to believe that you would support a
>> neighbor's right to keep nuclear weapons, biological weapons, and nerve
>> gas on his/her property.

>> If we cannot even agree on keeping weapons of mass destruction out of
>> the hands of individuals, can there be any hope for us?

>I don't sign any blank checks.

Of course.  The term must be rigidly defined in any bill.

>When Doug Foxvog says "weapons of mass destruction," he means CBW and
>nukes.  When Sarah Brady says "weapons of mass destruction" she means
>Street Sweeper shotguns and semi-automatic SKS rifles.

I doubt she uses this term for that.  You are using a quote allegedly
from her, can you back it up?

>When John
>Lawrence Rutledge says "weapons of mass destruction," and then immediately
>follows it with:

>>> The US has thousands of people killed each year by handguns,
>>> this number can easily be reduced by putting reasonable restrictions
>>> on them.

>...what does Rutledge mean by the term?

I read the article as presenting first an argument about weapons of mass
destruction (as commonly understood) and then switching to other topics.
The first point evidently was to show that not all weapons should be
allowed, and then the later analysis was, given this understanding, to
consider another class.

>cdt@rocket.sw.stratus.com   --If you believe that I speak for my company,
>OR cdt@vos.stratus.com        write today for my special Investors' Packet...



--
doug foxvog
douglas.foxvog@vtt.fi

========== Doc 6 ==========
From: bmdelane@quads.uchicago.edu (brian manning delaney)
Subject: Brain Tumor Treatment (thanks)
Reply-To: bmdelane@midway.uchicago.edu
Organization: University of Chicago
Lines: 12

There were a few people who responded to my request for info on
treatment for astrocytomas through email, whom I couldn't thank
directly because of mail-bouncing probs (Sean, Debra, and Sharon).  So
I thought I'd publicly thank everyone.

Thanks!

(I'm sure glad I accidentally hit "rn" instead of "rm" when I was
trying to delete a file last September. "Hmmm... 'News?' What's
this?"....)

-Brian

========== Doc 7 ==========
From: bgrubb@dante.nmsu.edu (GRUBB)
Subject: Re: IDE vs SCSI
Organization: New Mexico State University, Las Cruces, NM
Lines: 44
Distribution: world
NNTP-Posting-Host: dante.nmsu.edu

DXB132@psuvm.psu.edu writes:
>In article <1qlbrlINN7rk@dns1.NMSU.Edu>, bgrubb@dante.nmsu.edu (GRUBB) says:
>>In PC Magazine April 27, 1993:29 "Although SCSI is twice as fasst as ESDI,
>>20% faster than IDE, and support up to 7 devices its acceptance ...has
>>long been stalled by incompatability problems and installation headaches."

>I love it when magazine writers make stupid statements like that re:
>performance. Where do they get those numbers? I'll list the actual
>performance ranges, which should convince anyone that such a
>statement is absurd:
>SCSI-I ranges from 0-5MB/s.
>SCSI-II ranges from 0-40MB/s.
>IDE ranges from 0-8.3MB/s.
>ESDI is always 1.25MB/s (although there are some non-standard versions)
ALL this shows is that YOU don't know much about SCSI.

SCSI-1 {with a SCSI-1 controler chip} range is indeed 0-5MB/s
and that is ALL you have right about SCSI
SCSI-1 {With a SCSI-2 controller chip}: 4-6MB/s with 10MB/s burst {8-bit}
 Note the INCREASE in SPEED, the Mac Quadra uses this version of SCSI-1
 so it DOES exist. Some PC use this set up too.
SCSI-2 {8-bit/SCSI-1 mode}:          4-6MB/s with 10MB/s burst
SCSI-2 {16-bit/wide or fast mode}:  8-12MB/s with 20MB/s burst
SCSI-2 {32-bit/wide AND fast}:     15-20MB/s with 40MB/s burst

By your OWN data the "Although SCSI is twice as fast as ESDI" is correct
With a SCSI-2 controller chip SCSI-1 can reach 10MB/s which is indeed
"20% faster than IDE" {120% of 8.3 is 9.96}. ALL these SCSI facts have been
posted to this newsgroup in my Mac & IBM info sheet {available by FTP on
sumex-aim.stanford.edu (36.44.0.6) in the info-mac/report as
mac-ibm-compare[version #].txt (It should be 173 but 161 may still be there)}

Part of this problem is both Mac and IBM PC are inconsiant about what SCSI
is which.  Though it is WELL documented that the Quadra has a SCSI-2 chip
an Apple salesperson said "it uses a fast SCSI-1 chip" {Not at a 6MB/s,
10MB/s burst it does not. SCSI-1 is 5MB/s maximum synchronous and Quadra
uses ANsynchronous SCSI which is SLOWER}  It seems that Mac and IBM see
SCSI-1 interface and think 'SCSI-1' when it maybe a SCSI-1 interface driven
in the machine by a SCSi-2 controller chip in 8-bit mode {Which is MUCH
FASTER then true SCSI-1 can go}.

Don't slam an article because you don't understand what is going on.
One reference for the Quadra's SCSI-2 controller chip is
(Digital Review, Oct 21, 1991 v8 n33 p8(1)).

========== Doc 8 ==========
From: holmes7000@iscsvax.uni.edu
Subject: WIn 3.0 ICON HELP PLEASE!
Organization: University of Northern Iowa
Lines: 10

I have win 3.0 and downloaded several icons and BMP's but I can't figure out
how to change the "wallpaper" or use the icons.  Any help would be appreciated.


Thanx,

-Brando

PS Please E-mail me


========== Doc 9 ==========
From: kerr@ux1.cso.uiuc.edu (Stan Kerr)
Subject: Re: Sigma Designs Double up??
Article-I.D.: ux1.C52u8x.B62
Organization: University of Illinois at Urbana
Lines: 29

jap10@po.CWRU.Edu (Joseph A. Pellettiere) writes:


>	I am looking for any information about the Sigma Designs
>	double up board.  All I can figure out is that it is a
>	hardware compression board that works with AutoDoubler, but
>	I am not sure about this.  Also how much would one cost?

I've had the board for over a year, and it does work with Diskdoubler,
but not with Autodoubler, due to a licensing problem with Stac Technologies,
the owners of the board's compression technology. (I'm writing this
from memory; I've lost the reference. Please correct me if I'm wrong.)

Using the board, I've had problems with file icons being lost, but it's
hard to say whether it's the board's fault or something else; however,
if I decompress the troubled file and recompress it without the board,
the icon usually reappears. Because of the above mentioned licensing
problem, the freeware expansion utility DD Expand will not decompress
a board-compressed file unless you have the board installed.

Since Stac has its own product now, it seems unlikely that the holes
in Autodoubler/Diskdoubler related to the board will be fixed.
Which is sad, and makes me very reluctant to buy Stac's product since
they're being so stinky. (But hey, that's competition.)
--

Stan Kerr
Computing & Communications Services Office, U of Illinois/Urbana
Phone: 217-333-5217  Email: stankerr@uiuc.edu

========== Doc 10 ==========
From: irwin@cmptrc.lonestar.org (Irwin Arnstein)
Subject: Re: Recommendation on Duc
Summary: What's it worth?
Distribution: usa
Expires: Sat, 1 May 1993 05:00:00 GMT
Organization: CompuTrac Inc., Richardson TX
Keywords: Ducati, GTS, How much?
Lines: 13

I have a line on a Ducati 900GTS 1978 model with 17k on the clock.  Runs
very well, paint is the bronze/brown/orange faded out, leaks a bit of oil
and pops out of 1st with hard accel.  The shop will fix trans and oil
leak.  They sold the bike to the 1 and only owner.  They want $3495, and
I am thinking more like $3K.  Any opinions out there?  Please email me.
Thanks.  It would be a nice stable mate to the Beemer.  Then I'll get
a jap bike and call myself Axis Motors!

--
-----------------------------------------------------------------------
"Tuba" (Irwin)      "I honk therefore I am"     CompuTrac-Richardson,Tx
irwin@cmptrc.lonestar.org    DoD #0826          (R75/6)
-----------------------------------------------------------------------

========== Doc 11 ==========
From: david@terminus.ericsson.se (David Bold)
Subject: Re: Question for those with popular morality
Reply-To: david@terminus.ericsson.se
Distribution: world
Organization: Camtec Electronics (Ericsson), Leicester, England
Lines: 77
Nntp-Posting-Host: bangkok

In article 17570@freenet.carleton.ca, ad354@Freenet.carleton.ca (James Owens) writes:
>
>In a previous article, david@terminus.ericsson.se (David Bold) says:
>
>>
>>I don't mean to be rude, but I think that you've got hold of the wrong
>>end of a different stick...
>>
>>David
>
>I had a look at your posting again and I see what you mean!  I was so
>intent on explaining how Jung thought we could be more moral than God that
>I overlooked your main line of thought.
>
>You seem to be saying that, God being unknowable, His morality is unknowable.

Yep, that's pretty much it. I'm not a Jew but I understand that this is the
Jewish way of thinking. However, the Jews believe that the Covenant between
YHWH and the Patriarchs (Abraham and Moses, in this case) establishes a Moral
Code to follow for mankind. Even the Jews could not decide where the boundaries
fall, though.

As I understand it, the Sadducees believed that the Torah was all that was
required, whereas the Pharisees (the ancestors of modern Judaism) believed that
the Torah was available for interpretation to lead to an understanding of
the required Morality in all its nuances (->Talmud).

The essence of all of this is that Biblical Morality is an interface between
Man and YHWH (for a Jew or Christian) and does not necessarily indicate
anything about YHWH outside of that relationship (although one can speculate).

>
>The first thing that comes to mind is that man is supposed to be created
>in His image, so there is an argument that we are committed to whatever
>moral code He follows as part of trying to live up to that image.  If we
>are supposed to live by Christ's example, you would be hard pressed to
>argue that God is a "do what I say, not what I do" kind of guy.

The trouble with all of this is that we don't really know what the "created
in His image" means. I've heard a number of different opinions on this and
have still not come to any conclusion. This rather upsets the Apple Cart if
one wants to base a Life Script on this shaky foundation (to mix metaphors
unashamedly!) As to living by Christ's example, we know very little about
Jesus as a person. We only have his recorded utterances in a set of narratives
by his followers, and some very small references from comtemporary historians.
Revelation aside, one can only "know" Christ second-hand or worse.

This is not an attempt to debunk Christianity (although it may seem that way
initially), the point I`m trying to make is that we only really have the Bible
to interpret, and that interpretation is by humanity. I guess this is where
Faith or Relevation comes in with all its inherent subjectiveness.

>
>Metaphysically, if there are multiple moral codes then there is no
>Absolute moral code, and I think this is theologically questionable.

No. There may be an absolute moral code. There are undoubtably multiple
moral codes. The multiple moral codes may be founded in the absolute moral
code. As an example, a parent may tell a child never to swear, and the child
may assume that the parent never swears simply because the parent has told
the child that it is "wrong". Now, the parent may swear like a trooper in
the pub or bar (where there are no children). The "wrongness" here is if
the child disobeys the parent. The parent may feel that it is "inappropriate"
to swear in front of children but may be quite happy to swear in front of
animals. The analogy does not quite hold water because the child knows that
he is of the same type as the parent (and may be a parent later in life) but
you get the gist of it? Incidentally, the young child considers the directive
as absolute until he gets older (see Piaget) and learns a morality of his own.

David.

---
On religion:

"Oh, where is the sea?", the fishes cried,
As they swam its clearness through.


========== Doc 12 ==========
From: rodc@fc.hp.com (Rod Cerkoney)
Subject: *$G4qxF,fekVH6
Nntp-Posting-Host: hpfcmrc.fc.hp.com
Organization: Hewlett Packard, Fort Collins, CO
X-Newsreader: TIN [version 1.1 PL8.5]
Lines: 15



--


Regards,
Rod Cerkoney
                                                        /\
______________________________________________         /~~\
                                                      /    \
  Rod Cerkoney MS 37     email:                      /      \
  Hewlett Packard         rodc@fc.hp.com        /\  /        \
  3404 East Harmony Rd.  Hpdesk:               /  \/          \    /\
  Fort Collins, CO 80525  HP4000/UX           /    \           \  /  \
_____________________________________________/      \           \/    \__

========== Doc 13 ==========
From: dbm0000@tm0006.lerc.nasa.gov (David B. Mckissock)
Subject: Re: Space Station Redesign, JSC Alternative #4
Organization: NASA Lewis Research Center / Cleveland, Ohio
Lines: 102
Distribution: world
NNTP-Posting-Host: tm0006.lerc.nasa.gov
News-Software: VAX/VMS VNEWS 1.41

In article <1993Apr23.184732.1105@aio.jsc.nasa.gov>, kjenks@gothamcity.jsc.nasa.gov writes...

   {Description of "External Tank" option for SSF redesign deleted}

>Mark proposed this design at Joe Shea's committee in Crystal City,
>and he reports that he was warmly received.  However, the rumors
>I hear say that a design based on a wingless Space Shuttle Orbiter

In [16]:
len(corpus)

15

Observações:
* cada email é um documento
* o corpus vai ser formado pelos 15 documentos

###  Passos para serem implementados

* realizar processo da tokenização
* retirar palavras sem relevância com o stopword
* vetorização
* extração de características TF, IDF, TF - IDF

In [17]:
nltk.download('punkt_tab')
nltk.download('stopwords')

stop_words = stopwords.words('english')

doc_tokens = []

for doc in corpus:
  tokenizacao = [token.lower() for token in word_tokenize(doc, language= 'english') if token.lower() not in stop_words]
  doc_tokens.append(tokenizacao)

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [18]:
doc_tokens[0][:10]

[':', 'lerxst', '@', 'wam.umd.edu', '(', "'s", 'thing', ')', 'subject', ':']

In [19]:
# transformando as palavras em sentenças
text_line = [' '.join(doc) for doc in doc_tokens]
text_line[0]

": lerxst @ wam.umd.edu ( 's thing ) subject : car ! ? nntp-posting-host : rac3.wam.umd.edu organization : university maryland , college park lines : 15 wondering anyone could enlighten car saw day . 2-door sports car , looked late 60s/ early 70s . called bricklin . doors really small . addition , front bumper separate rest body . know . anyone tellme model name , engine specs , years production , car made , history , whatever info funky looking car , please e-mail . thanks , - il -- -- brought neighborhood lerxst -- --"

**Vetorização**

In [20]:
# vetorização
from sklearn.feature_extraction.text import CountVectorizer

# retorna um vetor aonde cada linha representa um documento, cada coluna representa um termo e os valores são quantas vezes cada palavra aparece no respectivo documento
# ele tokeniza o texto quebrando em palavras

count_vectors = CountVectorizer(stop_words=None,min_df=0.005,max_df=0.5,max_features=3000)
count_vectors.fit(text_line)
print(f"Quantidade de documentos: {len(count_vectors.vocabulary_)} e Quantidade de palavras: {sum([doc[1] for doc in count_vectors.vocabulary_.items()])}")

Quantidade de documentos: 1371 e Quantidade de palavras: 939135

In [21]:
sorted(count_vectors.vocabulary_.items(),reverse=False)

[('00', np.int64(0)),
 ('000', np.int64(1)),
 ('05', np.int64(2)),
 ('0826', np.int64(3)),
 ('083057', np.int64(4)),
 ('10', np.int64(5)),
 ('1000', np.int64(6)),
 ('1000yds', np.int64(7)),
 ('102', np.int64(8)),
 ('10mb', np.int64(9)),
 ('11', np.int64(10)),
 ('1105', np.int64(11)),
 ('12', np.int64(12)),
 ('120', np.int64(13)),
 ('1200x', np.int64(14)),
 ('12mb', np.int64(15)),
 ('13', np.int64(16)),
 ('14', np.int64(17)),
 ('1400', np.int64(18)),
 ('15', np.int64(19)),
 ('16', np.int64(20)),
 ('160', np.int64(21)),
 ('161', np.int64(22)),
 ('16899', np.int64(23)),
 ('173', np.int64(24)),
 ('17570', np.int64(25)),
 ('17k', np.int64(26)),
 ('180', np.int64(27)),
 ('184732', np.int64(28)),
 ('185c', np.int64(29)),
 ('1978', np.int64(30)),
 ('1985', np.int64(31)),
 ('1991', np.int64(32)),
 ('1993', np.int64(33)),
 ('1993apr20', np.int64(34)),
 ('1993apr23', np.int64(35)),
 ('1qlbrlinn7rk', np.int64(36)),
 ('1qv87v', np.int64(37)),
 ('1qvfo9innc3s', np.int64(38)),
 ('1r1eu1', np.int64(39)),
 ('1st', np.int64(40)),
 ('20', np.int64(41)),
 ('20mb', np.int64(42)),
 ('21', np.int64(43)),
 ('213', np.int64(44)),
 ('217', np.int64(45)),
 ('23', np.int64(46)),
 ('24', np.int64(47)),
 ('25', np.int64(48)),
 ('25mb', np.int64(49)),
 ('26', np.int64(50)),
 ('27', np.int64(51)),
 ('29', np.int64(52)),
 ('2nd', np.int64(53)),
 ('30', np.int64(54)),
 ('32', np.int64(55)),
 ('333', np.int64(56)),
 ('3404', np.int64(57)),
 ('3495', np.int64(58)),
 ('36', np.int64(59)),
 ('37', np.int64(60)),
 ('3k', np.int64(61)),
 ('3mb', np.int64(62)),
 ('3rd', np.int64(63)),
 ('40mb', np.int64(64)),
 ('41', np.int64(65)),
 ('44', np.int64(66)),
 ('4h9', np.int64(67)),
 ('4j3', np.int64(68)),
 ('4t', np.int64(69)),
 ('50', np.int64(70)),
 ('51', np.int64(71)),
 ('512k', np.int64(72)),
 ('5217', np.int64(73)),
 ('525ft', np.int64(74)),
 ('58', np.int64(75)),
 ('5mb', np.int64(76)),
 ('60', np.int64(77)),
 ('60s', np.int64(78)),
 ('6mb', np.int64(79)),
 ('70s', np.int64(80)),
 ('734340159', np.int64(81)),
 ('77', np.int64(82)),
 ('7x35', np.int64(83)),
 ('80', np.int64(84)),
 ('800', np.int64(85)),
 ('80525', np.int64(86)),
 ('80mb', np.int64(87)),
 ('900gts', np.int64(88)),
 ('92', np.int64(89)),
 ('96', np.int64(90)),
 ('__', np.int64(91)),
 ('_____________________________________________', np.int64(92)),
 ('______________________________________________', np.int64(93)),
 ('abraham', np.int64(94)),
 ('abraxis', np.int64(95)),
 ('absolute', np.int64(96)),
 ('absurd', np.int64(97)),
 ('accel', np.int64(98)),
 ('acceleration', np.int64(99)),
 ('acceptance', np.int64(100)),
 ('access', np.int64(101)),
 ('accessories', np.int64(102)),
 ('accidental', np.int64(103)),
 ('accidentally', np.int64(104)),
 ('achieved', np.int64(105)),
 ('acrv', np.int64(106)),
 ('acsu', np.int64(107)),
 ('active', np.int64(108)),
 ('activities', np.int64(109)),
 ('actual', np.int64(110)),
 ('actually', np.int64(111)),
 ('ad354', np.int64(112)),
 ('adapters', np.int64(113)),
 ('add', np.int64(114)),
 ('added', np.int64(115)),
 ('addition', np.int64(116)),
 ('address', np.int64(117)),
 ('adds', np.int64(118)),
 ('adopted', np.int64(119)),
 ('advance', np.int64(120)),
 ('advisory', np.int64(121)),
 ('agree', np.int64(122)),
 ('aim', np.int64(123)),
 ('aio', np.int64(124)),
 ('air', np.int64(125)),
 ('allegedly', np.int64(126)),
 ('allowed', np.int64(127)),
 ('alot', np.int64(128)),
 ('already', np.int64(129)),
 ('also', np.int64(130)),
 ('alternative', np.int64(131)),
 ('although', np.int64(132)),
 ('always', np.int64(133)),
 ('am', np.int64(134)),
 ('amber', np.int64(135)),
 ('amendment', np.int64(136)),
 ('analogy', np.int64(137)),
 ('analysis', np.int64(138)),
 ('ancestors', np.int64(139)),
 ('angle', np.int64(140)),
 ('animals', np.int64(141)),
 ('another', np.int64(142)),
 ('answer', np.int64(143)),
 ('answered', np.int64(144)),
 ('ansynchronous', np.int64(145)),
 ('anybody', np.int64(146)),
 ('anymore', np.int64(147)),
 ('anyone', np.int64(148)),
 ('anything', np.int64(149)),
 ('appearence', np.int64(150)),
 ('apple', np.int64(151)),
 ('appreciated', np.int64(152)),
 ('approach', np.int64(153)),
 ('approximately', np.int64(154)),
 ('april', np.int64(155)),
 ('argue', np.int64(156)),
 ('argument', np.int64(157)),
 ('arnstein', np.int64(158)),
 ('around', np.int64(159)),
 ('arrays', np.int64(160)),
 ('arrow', np.int64(161)),
 ('as', np.int64(162)),
 ('aside', np.int64(163)),
 ('ask', np.int64(164)),
 ('assembly', np.int64(165)),
 ('assume', np.int64(166)),
 ('assumes', np.int64(167)),
 ('assured', np.int64(168)),
 ('astrocytomas', np.int64(169)),
 ('astrophysical', np.int64(170)),
 ('attached', np.int64(171)),
 ('attained', np.int64(172)),
 ('attempt', np.int64(173)),
 ('autodoubler', np.int64(174)),
 ('automatic', np.int64(175)),
 ('available', np.int64(176)),
 ('axis', np.int64(177)),
 ('b62', np.int64(178)),
 ('back', np.int64(179)),
 ('backside', np.int64(180)),
 ('bag', np.int64(181)),
 ('baker', np.int64(182)),
 ('band', np.int64(183)),
 ('bangkok', np.int64(184)),
 ('bar', np.int64(185)),
 ('base', np.int64(186)),
 ('based', np.int64(187)),
 ('basically', np.int64(188)),
 ('bear', np.int64(189)),
 ('beemer', np.int64(190)),
 ('behalf', np.int64(191)),
 ('believe', np.int64(192)),
 ('believed', np.int64(193)),
 ('berthing', np.int64(194)),
 ('bet', np.int64(195)),
 ('better', np.int64(196)),
 ('bgrubb', np.int64(197)),
 ('bible', np.int64(198)),
 ('biblical', np.int64(199)),
 ('bike', np.int64(200)),
 ('bill', np.int64(201)),
 ('binoculars', np.int64(202)),
 ('binolux', np.int64(203)),
 ('biological', np.int64(204)),
 ('bit', np.int64(205)),
 ('black', np.int64(206)),
 ('blank', np.int64(207)),
 ('blender', np.int64(208)),
 ('bmdelane', np.int64(209)),
 ('bmp', np.int64(210)),
 ('board', np.int64(211)),
 ('body', np.int64(212)),
 ('bold', np.int64(213)),
 ('bouncing', np.int64(214)),
 ('boundaries', np.int64(215)),
 ('brady', np.int64(216)),
 ('brain', np.int64(217)),
 ('brand', np.int64(218)),
 ('brando', np.int64(219)),
 ('brave', np.int64(220)),
 ('breifly', np.int64(221)),
 ('brian', np.int64(222)),
 ('bricklin', np.int64(223)),
 ('brief', np.int64(224)),
 ('bro', np.int64(225)),
 ('bronze', np.int64(226)),
 ('brother', np.int64(227)),
 ('brought', np.int64(228)),
 ('brown', np.int64(229)),
 ('buffalo', np.int64(230)),
 ('bugs', np.int64(231)),
 ('build', np.int64(232)),
 ('building', np.int64(233)),
 ('bumper', np.int64(234)),
 ('bunch', np.int64(235)),
 ('burst', np.int64(236)),
 ('bus', np.int64(237)),
 ('buy', np.int64(238)),
 ('c52u8x', np.int64(239)),
 ('c5jlwx', np.int64(240)),
 ('c5n3gi', np.int64(241)),
 ('c5owcb', np.int64(242)),
 ('ca', np.int64(243)),
 ('call', np.int64(244)),
 ('called', np.int64(245)),
 ('cambridge', np.int64(246)),
 ('camtec', np.int64(247)),
 ('capability', np.int64(248)),
 ('car', np.int64(249)),
 ('cards', np.int64(250)),
 ('carleton', np.int64(251)),
 ('carson', np.int64(252)),
 ('cart', np.int64(253)),
 ('case', np.int64(254)),
 ('cassette', np.int64(255)),
 ('caution', np.int64(256)),
 ('cbw', np.int64(257)),
 ('cdt', np.int64(258)),
 ('center', np.int64(259)),
 ('centerline', np.int64(260)),
 ('cerkoney', np.int64(261)),
 ('cfa', np.int64(262)),
 ('change', np.int64(263)),
 ('changes', np.int64(264)),
 ('channels', np.int64(265)),
 ('checked', np.int64(266)),
 ('checkout', np.int64(267)),
 ('checks', np.int64(268)),
 ('chicago', np.int64(269)),
 ('child', np.int64(270)),
 ('children', np.int64(271)),
 ('chip', np.int64(272)),
 ('christ', np.int64(273)),
 ('christian', np.int64(274)),
 ('christianity', np.int64(275)),
 ('city', np.int64(276)),
 ('class', np.int64(277)),
 ('class1', np.int64(278)),
 ('clear', np.int64(279)),
 ('clearness', np.int64(280)),
 ('cleveland', np.int64(281)),
 ('clock', np.int64(282)),
 ('cmptrc', np.int64(283)),
 ('cmu', np.int64(284)),
 ('co', np.int64(285)),
 ('code', np.int64(286)),
 ('codes', np.int64(287)),
 ('college', np.int64(288)),
 ('collins', np.int64(289)),
 ('com', np.int64(290)),
 ('come', np.int64(291)),
 ('comes', np.int64(292)),
 ('coming', np.int64(293)),
 ('command', np.int64(294)),
 ('committed', np.int64(295)),
 ('committee', np.int64(296)),
 ('common', np.int64(297)),
 ('commonly', np.int64(298)),
 ('communications', np.int64(299)),
 ('company', np.int64(300)),
 ('compare', np.int64(301)),
 ('competition', np.int64(302)),
 ('complete', np.int64(303)),
 ('compressed', np.int64(304)),
 ('compression', np.int64(305)),
 ('computed', np.int64(306)),
 ('computer', np.int64(307)),
 ('computing', np.int64(308)),
 ('computrac', np.int64(309)),
 ('comtemporary', np.int64(310)),
 ('conclusion', np.int64(311)),
 ('conditions', np.int64(312)),
 ('cone', np.int64(313)),
 ('connor', np.int64(314)),
 ('consider', np.int64(315)),
 ('considered', np.int64(316)),
 ('considers', np.int64(317)),
 ('contact', np.int64(318)),
 ('control', np.int64(319)),
 ('controler', np.int64(320)),
 ('controller', np.int64(321)),
 ('convictions', np.int64(322)),
 ('convince', np.int64(323)),
 ('cookbook', np.int64(324)),
 ('core', np.int64(325)),
 ('corner', np.int64(326)),
 ('corporation', np.int64(327)),
 ('correct', np.int64(328)),
 ('cost', np.int64(329)),
 ('could', np.int64(330)),
 ('count', np.int64(331)),
 ('course', np.int64(332)),
 ('covenant', np.int64(333)),
 ('cpu', np.int64(334)),
 ('created', np.int64(335)),
 ('crew', np.int64(336)),
 ('cried', np.int64(337)),
 ('crimial', np.int64(338)),
 ('cruces', np.int64(339)),
 ('crystal', np.int64(340)),
 ('cs', np.int64(341)),
 ('csd', np.int64(342)),
 ('cso', np.int64(343)),
 ('cubic', np.int64(344)),
 ('curious', np.int64(345)),
 ('currently', np.int64(346)),
 ('cwru', np.int64(347)),
 ('cylinder', np.int64(348)),
 ('daily', np.int64(349)),
 ('dangerous', np.int64(350)),
 ('dante', np.int64(351)),
 ('data', np.int64(352)),
 ('david', np.int64(353)),
 ('day', np.int64(354)),
 ('days', np.int64(355)),
 ('dbm0000', np.int64(356)),
 ('dd', np.int64(357)),
 ('deaths', np.int64(358)),
 ('debra', np.int64(359)),
 ('debris', np.int64(360)),
 ('debunk', np.int64(361)),
 ('decide', np.int64(362)),
 ('deck', np.int64(363)),
 ('decker', np.int64(364)),
 ('decompress', np.int64(365)),
 ('defined', np.int64(366)),
 ('degradation', np.int64(367)),
 ('delaney', np.int64(368)),
 ('delete', np.int64(369)),
 ('deleted', np.int64(370)),
 ('deployed', np.int64(371)),
 ('derived', np.int64(372)),
 ('description', np.int64(373)),
 ('design', np.int64(374)),
 ('designs', np.int64(375)),
 ('destruction', np.int64(376)),
 ('destructive', np.int64(377)),
 ('detailing', np.int64(378)),
 ('developed', np.int64(379)),
 ('devices', np.int64(380)),
 ('dfo', np.int64(381)),
 ('diameter', np.int64(382)),
 ('different', np.int64(383)),
 ('digital', np.int64(384)),
 ('directive', np.int64(385)),
 ('directly', np.int64(386)),
 ('dirt', np.int64(387)),
 ('disagree', np.int64(388)),
 ('disk', np.int64(389)),
 ('diskdoubler', np.int64(390)),
 ('disobeys', np.int64(391)),
 ('display', np.int64(392)),
 ('distribution', np.int64(393)),
 ('division', np.int64(394)),
 ('dns1', np.int64(395)),
 ('docked', np.int64(396)),
 ('docking', np.int64(397)),
 ('documented', np.int64(398)),
 ('dod', np.int64(399)),
 ('done', np.int64(400)),
 ('door', np.int64(401)),
 ('doors', np.int64(402)),
 ('double', np.int64(403)),
 ('doubt', np.int64(404)),
 ('doug', np.int64(405)),
 ('douglas', np.int64(406)),
 ('downloaded', np.int64(407)),
 ('driven', np.int64(408)),
 ('dropped', np.int64(409)),
 ('drops', np.int64(410)),
 ('dry', np.int64(411)),
 ('dryer', np.int64(412)),
 ('dual', np.int64(413)),
 ('dubing', np.int64(414)),
 ('duc', np.int64(415)),
 ('ducati', np.int64(416)),
 ('due', np.int64(417)),
 ('dumb', np.int64(418)),
 ('duo', np.int64(419)),
 ('duster', np.int64(420)),
 ('dxb132', np.int64(421)),
 ('early', np.int64(422)),
 ('easily', np.int64(423)),
 ('east', np.int64(424)),
 ('ec', np.int64(425)),
 ('ecn', np.int64(426)),
 ('edition', np.int64(427)),
 ('electrical', np.int64(428)),
 ('electronics', np.int64(429)),
 ('else', np.int64(430)),
 ('elv', np.int64(431)),
 ('email', np.int64(432)),
 ('end', np.int64(433)),
 ('enemies', np.int64(434)),
 ('engine', np.int64(435)),
 ('engineering', np.int64(436)),
 ('engines', np.int64(437)),
 ('england', np.int64(438)),
 ('enlighten', np.int64(439)),
 ('environment', np.int64(440)),
 ('environmental', np.int64(441)),
 ('equalizer', np.int64(442)),
 ('ericsson', np.int64(443)),
 ('error', np.int64(444)),
 ('errors', np.int64(445)),
 ('esa', np.int64(446)),
 ('esdi', np.int64(447)),
 ('especially', np.int64(448)),
 ('essence', np.int64(449)),
 ('establishes', np.int64(450)),
 ('etrat', np.int64(451)),
 ('eva', np.int64(452)),
 ('even', np.int64(453)),
 ('every', np.int64(454)),
 ('everylast', np.int64(455)),
 ('everyone', np.int64(456)),
 ('evidently', np.int64(457)),
 ('example', np.int64(458)),
 ('exception', np.int64(459)),
 ('exist', np.int64(460)),
 ('existant', np.int64(461)),
 ('existing', np.int64(462)),
 ('expand', np.int64(463)),
 ('expansion', np.int64(464)),
 ('expected', np.int64(465)),
 ('expeditously', np.int64(466)),
 ('experiences', np.int64(467)),
 ('expires', np.int64(468)),
 ('explaining', np.int64(469)),
 ('external', np.int64(470)),
 ('extra', np.int64(471)),
 ('f8f', np.int64(472)),
 ('facts', np.int64(473)),
 ('faded', np.int64(474)),
 ('failures', np.int64(475)),
 ('fair', np.int64(476)),
 ('faith', np.int64(477)),
 ('fall', np.int64(478)),
 ('far', np.int64(479)),
 ('fasst', np.int64(480)),
 ('fast', np.int64(481)),
 ('faster', np.int64(482)),
 ('fault', np.int64(483)),
 ('fc', np.int64(484)),
 ('features', np.int64(485)),
 ('feel', np.int64(486)),
 ('feet', np.int64(487)),
 ('fekvh6', np.int64(488)),
 ('fi', np.int64(489)),
 ('figure', np.int64(490)),
 ('figured', np.int64(491)),
 ('file', np.int64(492)),
 ('fill', np.int64(493)),
 ('final', np.int64(494)),
 ('finally', np.int64(495)),
 ('finals', np.int64(496)),
 ('find', np.int64(497)),
 ('finish', np.int64(498)),
 ('first', np.int64(499)),
 ('fishes', np.int64(500)),
 ('fix', np.int64(501)),
 ('fixable', np.int64(502)),
 ('fixed', np.int64(503)),
 ('flies', np.int64(504)),
 ('flights', np.int64(505)),
 ('floors', np.int64(506)),
 ('floppies', np.int64(507)),
 ('floppy', np.int64(508)),
 ('fm', np.int64(509)),
 ('folks', np.int64(510)),
 ('follow', np.int64(511)),
 ('followers', np.int64(512)),
 ('follows', np.int64(513)),
 ('force', np.int64(514)),
 ('forsale', np.int64(515)),
 ('fort', np.int64(516)),
 ('foundation', np.int64(517)),
 ('founded', np.int64(518)),
 ('four', np.int64(519)),
 ('foxvog', np.int64(520)),
 ('freedom', np.int64(521)),
 ('freenet', np.int64(522)),
 ('freeware', np.int64(523)),
 ('front', np.int64(524)),
 ('ft', np.int64(525)),
 ('ftp', np.int64(526)),
 ('fuel', np.int64(527)),
 ('functionality', np.int64(528)),
 ('funky', np.int64(529)),
 ('g4qxf', np.int64(530)),
 ('gas', np.int64(531)),
 ('gave', np.int64(532)),
 ('get', np.int64(533)),
 ('gets', np.int64(534)),
 ('ghost', np.int64(535)),
 ('giant', np.int64(536)),
 ('gist', np.int64(537)),
 ('given', np.int64(538)),
 ('glad', np.int64(539)),
 ('gmt', np.int64(540)),
 ('gn', np.int64(541)),
 ('go', np.int64(542)),
 ('god', np.int64(543)),
 ('goes', np.int64(544)),
 ('going', np.int64(545)),
 ('good', np.int64(546)),
 ('got', np.int64(547)),
 ('gothamcity', np.int64(548)),
 ('gov', np.int64(549)),
 ('government', np.int64(550)),
 ('graceful', np.int64(551)),
 ('graphics', np.int64(552)),
 ('great', np.int64(553)),
 ('green', np.int64(554)),
 ('griffin', np.int64(555)),
 ('ground', np.int64(556)),
 ('grubb', np.int64(557)),
 ('gts', np.int64(558)),
 ('guess', np.int64(559)),
 ('guy', np.int64(560)),
 ('guykuo', np.int64(561)),
 ('habitability', np.int64(562)),
 ('habitation', np.int64(563)),
 ('hair', np.int64(564)),
 ('hand', np.int64(565)),
 ('handguns', np.int64(566)),
 ('hands', np.int64(567)),
 ('happy', np.int64(568)),
 ('hard', np.int64(569)),
 ('hardware', np.int64(570)),
 ('harmony', np.int64(571)),
 ('harris', np.int64(572)),
 ('harvard', np.int64(573)),
 ('head', np.int64(574)),
 ('headaches', np.int64(575)),
 ('hear', np.int64(576)),
 ('heard', np.int64(577)),
 ('heat', np.int64(578)),
 ('hellcats', np.int64(579)),
 ('help', np.int64(580)),
 ('helpful', np.int64(581)),
 ('helping', np.int64(582)),
 ('her', np.int64(583)),
 ('hewlett', np.int64(584)),
 ('hey', np.int64(585)),
 ('high', np.int64(586)),
 ('his', np.int64(587)),
 ('historians', np.int64(588)),
 ('history', np.int64(589)),
 ('hit', np.int64(590)),
 ('hmmm', np.int64(591)),
 ('hold', np.int64(592)),
 ('holes', np.int64(593)),
 ('holmes7000', np.int64(594)),
 ('honk', np.int64(595)),
 ('hope', np.int64(596)),
 ('hopefully', np.int64(597)),
 ('hour', np.int64(598)),
 ('housekeeping', np.int64(599)),
 ('however', np.int64(600)),
 ('hp', np.int64(601)),
 ('hp4000', np.int64(602)),
 ('hpdesk', np.int64(603)),
 ('hpfcmrc', np.int64(604)),
 ('human', np.int64(605)),
 ('humanity', np.int64(606)),
 ('humor', np.int64(607)),
 ('iastate', np.int64(608)),
 ('ibm', np.int64(609)),
 ('icon', np.int64(610)),
 ('icons', np.int64(611)),
 ('ide', np.int64(612)),
 ('ideas', np.int64(613)),
 ('ignore', np.int64(614)),
 ('ii', np.int64(615)),
 ('il', np.int64(616)),
 ('illinois', np.int64(617)),
 ('image', np.int64(618)),
 ('immediately', np.int64(619)),
 ('impression', np.int64(620)),
 ('inappropriate', np.int64(621)),
 ('inc', np.int64(622)),
 ('incidentally', np.int64(623)),
 ('inclination', np.int64(624)),
 ('included', np.int64(625)),
 ('includes', np.int64(626)),
 ('incompatability', np.int64(627)),
 ('inconsiant', np.int64(628)),
 ('increase', np.int64(629)),
 ('increased', np.int64(630)),
 ('indeed', np.int64(631)),
 ('indicate', np.int64(632)),
 ('individual', np.int64(633)),
 ('individuals', np.int64(634)),
 ('info', np.int64(635)),
 ('information', np.int64(636)),
 ('inherent', np.int64(637)),
 ('initial', np.int64(638)),
 ('initially', np.int64(639)),
 ('installation', np.int64(640)),
 ('installed', np.int64(641)),
 ('instead', np.int64(642)),
 ('integration', np.int64(643)),
 ('intended', np.int64(644)),
 ('intent', np.int64(645)),
 ('interface', np.int64(646)),
 ('international', np.int64(647)),
 ('internationals', np.int64(648)),
 ('interpret', np.int64(649)),
 ('interpretation', np.int64(650)),
 ('into', np.int64(651)),
 ('introduce', np.int64(652)),
 ('introductions', np.int64(653)),
 ('investors', np.int64(654)),
 ('iowa', np.int64(655)),
 ('iron', np.int64(656)),
 ('irwin', np.int64(657)),
 ('is', np.int64(658)),
 ('iscsvax', np.int64(659)),
 ('james', np.int64(660)),
 ('jap', np.int64(661)),
 ('jap10', np.int64(662)),
 ('japan', np.int64(663)),
 ('jcm', np.int64(664)),
 ('jesus', np.int64(665)),
 ('jew', np.int64(666)),
 ('jewish', np.int64(667)),
 ('jews', np.int64(668)),
 ('jgreen', np.int64(669)),
 ('jllee', np.int64(670)),
 ('joe', np.int64(671)),
 ('john', np.int64(672)),
 ('johnny', np.int64(673)),
 ('jonathan', np.int64(674)),
 ('joseph', np.int64(675)),
 ('jrutledg', np.int64(676)),
 ('jsc', np.int64(677)),
 ('judaism', np.int64(678)),
 ('jung', np.int64(679)),
 ('keep', np.int64(680)),
 ('keeping', np.int64(681)),
 ('ken', np.int64(682)),
 ('kerr', np.int64(683)),
 ('key', np.int64(684)),
 ('keywords', np.int64(685)),
 ('killed', np.int64(686)),
 ('kind', np.int64(687)),
 ('kjenks', np.int64(688)),
 ('knew', np.int64(689)),
 ('know', np.int64(690)),
 ('knowledge', np.int64(691)),
 ('known', np.int64(692)),
 ('knows', np.int64(693)),
 ('kuo', np.int64(694)),
 ('kw', np.int64(695)),
 ('kyanko', np.int64(696)),
 ('lab', np.int64(697)),
 ('labs', np.int64(698)),
 ('language', np.int64(699)),
 ('larc', np.int64(700)),
 ('las', np.int64(701)),
 ('last', np.int64(702)),
 ('lastly', np.int64(703)),
 ('late', np.int64(704)),
 ('later', np.int64(705)),
 ('launch', np.int64(706)),
 ('launching', np.int64(707)),
 ('lawrence', np.int64(708)),
 ('lead', np.int64(709)),
 ('leak', np.int64(710)),
 ('leaks', np.int64(711)),
 ('learns', np.int64(712)),
 ('leather', np.int64(713)),
 ('lee', np.int64(714)),
 ('leicester', np.int64(715)),

In [22]:
X = count_vectors.transform(text_line)
print(X[0,:])

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 55 stored elements and shape (1, 1371)>
  Coords	Values
  (0, 19)	1
  (0, 78)	1
  (0, 80)	1
  (0, 116)	1
  (0, 148)	2
  (0, 212)	1
  (0, 223)	1
  (0, 228)	1
  (0, 234)	1
  (0, 245)	1
  (0, 249)	5
  (0, 288)	1
  (0, 330)	1
  (0, 354)	1
  (0, 401)	1
  (0, 402)	1
  (0, 422)	1
  (0, 435)	1
  (0, 439)	1
  (0, 524)	1
  (0, 529)	1
  (0, 589)	1
  (0, 616)	1
  (0, 635)	1
  (0, 690)	1
  :	:
  (0, 755)	1
  (0, 767)	1
  (0, 799)	1
  (0, 821)	1
  (0, 829)	1
  (0, 897)	1
  (0, 921)	1
  (0, 954)	1
  (0, 983)	1
  (0, 999)	1
  (0, 1030)	1
  (0, 1063)	1
  (0, 1081)	1
  (0, 1115)	1
  (0, 1135)	1
  (0, 1139)	1
  (0, 1207)	1
  (0, 1212)	1
  (0, 1217)	1
  (0, 1267)	2
  (0, 1276)	1
  (0, 1321)	2
  (0, 1334)	1
  (0, 1344)	1
  (0, 1361)	1

In [23]:
X.shape

(15, 1371)

In [24]:
# visualizando o token
count_vectors.get_feature_names_out()[20]

'16'

In [25]:
df_x = pd.DataFrame(X.toarray(),columns=count_vectors.get_feature_names_out()).T

df_x.reset_index(inplace=True)

df_x[df_x['index'] == '15']

   index  0  1  2  3  4  5  6  7  8  9  10  11  12  13  14
19    15  1  0  0  0  0  0  0  1  0  0   0   0   1   0   0

### TF

In [26]:
tf_transformer = TfidfTransformer(use_idf=False) #use_idf = False desabilita o processo do idf
X_tf = tf_transformer.fit_transform(X)

# Mostrar os resultados
feature_names = count_vectors.get_feature_names_out()
tf_array = X_tf.toarray()

print(X_tf[0,:])

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 55 stored elements and shape (1, 1371)>
  Coords	Values
  (0, 19)	0.10482848367219183
  (0, 78)	0.10482848367219183
  (0, 80)	0.10482848367219183
  (0, 116)	0.10482848367219183
  (0, 148)	0.20965696734438366
  (0, 212)	0.10482848367219183
  (0, 223)	0.10482848367219183
  (0, 228)	0.10482848367219183
  (0, 234)	0.10482848367219183
  (0, 245)	0.10482848367219183
  (0, 249)	0.5241424183609592
  (0, 288)	0.10482848367219183
  (0, 330)	0.10482848367219183
  (0, 354)	0.10482848367219183
  (0, 401)	0.10482848367219183
  (0, 402)	0.10482848367219183
  (0, 422)	0.10482848367219183
  (0, 435)	0.10482848367219183
  (0, 439)	0.10482848367219183
  (0, 524)	0.10482848367219183
  (0, 529)	0.10482848367219183
  (0, 589)	0.10482848367219183
  (0, 616)	0.10482848367219183
  (0, 635)	0.10482848367219183
  (0, 690)	0.10482848367219183
  :	:
  (0, 755)	0.10482848367219183
  (0, 767)	0.10482848367219183
  (0, 799)	0.10482848367219183
  (0, 821)	0.10482848367219183
  (0, 829)	0.10482848367219183
  (0, 897)	0.10482848367219183
  (0, 921)	0.10482848367219183
  (0, 954)	0.10482848367219183
  (0, 983)	0.10482848367219183
  (0, 999)	0.10482848367219183
  (0, 1030)	0.10482848367219183
  (0, 1063)	0.10482848367219183
  (0, 1081)	0.10482848367219183
  (0, 1115)	0.10482848367219183
  (0, 1135)	0.10482848367219183
  (0, 1139)	0.10482848367219183
  (0, 1207)	0.10482848367219183
  (0, 1212)	0.10482848367219183
  (0, 1217)	0.10482848367219183
  (0, 1267)	0.20965696734438366
  (0, 1276)	0.10482848367219183
  (0, 1321)	0.20965696734438366
  (0, 1334)	0.10482848367219183
  (0, 1344)	0.10482848367219183
  (0, 1361)	0.10482848367219183

In [27]:
df_x = pd.DataFrame(tf_array,columns=count_vectors.get_feature_names_out()).T

df_x.reset_index(inplace=True)

df_x[df_x['index'] == '15']

,index,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
19,15,0.104828,0.0,0.0,0.0,0.0,0.0,0.0,0.026463,0.0,0.0,0.0,0.0,0.104257,0.0,0.0

In [28]:
# Exibindo TF para cada documento
tf_values = {'documento':[],'palavras': [], 'TF':[]}

for i, doc in enumerate(tf_array):
    for palavra, tf in zip(feature_names, doc):
        if tf > 0:
            tf_values['palavras'].append(palavra)
            tf_values['TF'].append(tf)
            tf_values['documento'].append(i)


df_tf = pd.DataFrame(tf_values)
df_tf.head()

   documento  palavras        TF
0          0        15  0.104828
1          0       60s  0.104828
2          0       70s  0.104828
3          0  addition  0.104828
4          0    anyone  0.209657

In [29]:
df_tf[df_tf['palavras'] == '15']

      documento palavras        TF
0             0       15  0.104828
630           7       15  0.026463
1236         12       15  0.104257

### IDF

In [30]:
# calcular IDF
idf_transformer = TfidfTransformer()
idf_transformer.fit(X)

# Acessando os valores de IDF
idf_valores = idf_transformer.idf_
palavras = count_vectors.get_feature_names_out()

idf_valores

array([3.07944154, 3.07944154, 3.07944154, ..., 3.07944154, 3.07944154,
       3.07944154])

In [31]:
# valores do IDF
idf_values = {'palavras': [], 'IDF':[]}

for doc_index, doc_vector in enumerate(X):
    doc_terms = doc_vector.toarray()[0]
    for i, count in enumerate(doc_terms):
        if count > 0:
            idf_values['palavras'].append(palavras[i])
            idf_values['IDF'].append(idf_valores[i])

df_idf = pd.DataFrame(idf_values)
df_idf.head()

   palavras       IDF
0        15  2.386294
1       60s  3.079442
2       70s  3.079442
3  addition  2.673976
4    anyone  2.386294

In [32]:
df_idf[df_idf['palavras'] == '15']

     palavras       IDF
0          15  2.386294
630        15  2.386294
1236       15  2.386294

### TF-IDF

calculado através do countVectorizer

In [33]:
# calculando o TF-IDF

tfidf_transformer = TfidfTransformer()
tfidf_transformer.fit(X)

X_tfidf = tfidf_transformer.transform(X)
x_tfidf_array = X_tfidf.toarray()

# Mostrar os resultados
feature_names_tfidf = count_vectors.get_feature_names_out()

print(X_tfidf[0,:])

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 55 stored elements and shape (1, 1371)>
  Coords	Values
  (0, 19)	0.08637780720678319
  (0, 78)	0.11146797818645814
  (0, 80)	0.11146797818645814
  (0, 116)	0.0967911690266661
  (0, 148)	0.17275561441356638
  (0, 212)	0.0967911690266661
  (0, 223)	0.11146797818645814
  (0, 228)	0.11146797818645814
  (0, 234)	0.11146797818645814
  (0, 245)	0.11146797818645814
  (0, 249)	0.5573398909322906
  (0, 288)	0.11146797818645814
  (0, 330)	0.07830057626289824
  (0, 354)	0.07830057626289824
  (0, 401)	0.11146797818645814
  (0, 402)	0.11146797818645814
  (0, 422)	0.11146797818645814
  (0, 435)	0.11146797818645814
  (0, 439)	0.11146797818645814
  (0, 524)	0.0967911690266661
  (0, 529)	0.11146797818645814
  (0, 589)	0.11146797818645814
  (0, 616)	0.11146797818645814
  (0, 635)	0.07830057626289824
  (0, 690)	0.06128763622710822
  :	:
  (0, 755)	0.07830057626289824
  (0, 767)	0.11146797818645814
  (0, 799)	0.0967911690266661
  (0, 821)	0.11146797818645814
  (0, 829)	0.11146797818645814
  (0, 897)	0.11146797818645814
  (0, 921)	0.06612113417107573
  (0, 954)	0.11146797818645814
  (0, 983)	0.11146797818645814
  (0, 999)	0.07170099804699114
  (0, 1030)	0.11146797818645814
  (0, 1063)	0.11146797818645814
  (0, 1081)	0.11146797818645814
  (0, 1115)	0.0967911690266661
  (0, 1135)	0.11146797818645814
  (0, 1139)	0.11146797818645814
  (0, 1207)	0.11146797818645814
  (0, 1212)	0.06128763622710822
  (0, 1217)	0.08637780720678319
  (0, 1267)	0.22293595637291627
  (0, 1276)	0.06128763622710822
  (0, 1321)	0.22293595637291627
  (0, 1334)	0.0967911690266661
  (0, 1344)	0.08637780720678319
  (0, 1361)	0.0967911690266661

In [34]:
tfidf_values = {'documento':[],'palavras':[],'TFIDF':[]}

for i, doc in enumerate(x_tfidf_array):
    for palavra, tf in zip(feature_names_tfidf, doc):
        if tf > 0:
            tfidf_values['palavras'].append(palavra)
            tfidf_values['TFIDF'].append(tf)
            tfidf_values['documento'].append(i)

df_tfidf = pd.DataFrame(tfidf_values)
df_tfidf.head()

   documento  palavras     TFIDF
0          0        15  0.086378
1          0       60s  0.111468
2          0       70s  0.111468
3          0  addition  0.096791
4          0    anyone  0.172756

In [35]:
df_tfidf[df_tfidf['palavras'] == '15']

      documento palavras     TFIDF
0             0       15  0.086378
630           7       15  0.021027
1236         12       15  0.083826

**Datframe Resultado**

In [38]:
df_resultado = pd.merge(df_tf,df_idf,on='palavras',how='inner')
df_resultado = pd.merge(df_resultado,df_tfidf,on=['palavras','documento'],how='inner')

df_resultado.drop_duplicates(inplace=True)

df_resultado.head()

   documento  palavras        TF       IDF     TFIDF
0          0        15  0.104828  2.386294  0.086378
3          0       60s  0.104828  3.079442  0.111468
4          0       70s  0.104828  3.079442  0.111468
5          0  addition  0.104828  2.673976  0.096791
7          0    anyone  0.209657  2.386294  0.172756

In [39]:
df_resultado[df_resultado['palavras'] == '15']

      documento palavras        TF       IDF     TFIDF
0             0       15  0.104828  2.386294  0.086378
1126          7       15  0.026463  2.386294  0.021027
2182         12       15  0.104257  2.386294  0.083826

Ordenando os casos com TFIDF de forma descrescente

In [40]:
df_resultado.sort_values(by='TFIDF',ascending=False,inplace=True)
df_resultado.head()
#

      documento palavras        TF       IDF     TFIDF
1327          7     scsi  0.793884  3.079442  0.814060
16            0      car  0.524142  3.079442  0.557340
1474          9    board  0.586210  2.673976  0.554392
1017          5  weapons  0.490653  3.079442  0.514316
543           3   harris  0.354943  3.079442  0.379422

Os 5 termos com maior TF-IDF significam que eles apresentam maior relevância sobre os seus respectivos documentos. Cada termo destacado se repete bastante no documento e faz parte do contexto que explica o texto. Exemplo:


* O termo **scsi** aparece bastante no documento zero e faz parte do contexto do texto que está conectado com a padronização de comunicação entre interfaces como os computadores.
* O termo **car** para o 2º maior TFIDF apresenta coerência com o texto pois o contexto do email se refere a um carro.

In [45]:
text_line[7]

": bgrubb @ dante.nmsu.edu ( grubb ) subject : : ide vs scsi organization : new mexico state university , las cruces , nm lines : 44 distribution : world nntp-posting-host : dante.nmsu.edu dxb132 @ psuvm.psu.edu writes : > article < 1qlbrlinn7rk @ dns1.nmsu.edu > , bgrubb @ dante.nmsu.edu ( grubb ) says : > > pc magazine april 27 , 1993:29 `` although scsi twice fasst esdi , > > 20 % faster ide , support 7 devices acceptance ... > > long stalled incompatability problems installation headaches . '' > love magazine writers make stupid statements like : > performance . get numbers ? 'll list actual > performance ranges , convince anyone > statement absurd : > scsi-i ranges 0-5mb/s . > scsi-ii ranges 0-40mb/s . > ide ranges 0-8.3mb/s . > esdi always 1.25mb/s ( although non-standard versions ) shows n't know much scsi . scsi-1 { scsi-1 controler chip } range indeed 0-5mb/s right scsi scsi-1 { scsi-2 controller chip } : 4-6mb/s 10mb/s burst { 8-bit } note increase speed , mac quadra uses version scsi-1 exist . pc use set . scsi-2 { 8-bit/scsi-1 mode } : 4-6mb/s 10mb/s burst scsi-2 { 16-bit/wide fast mode } : 8-12mb/s 20mb/s burst scsi-2 { 32-bit/wide fast } : 15-20mb/s 40mb/s burst data `` although scsi twice fast esdi '' correct scsi-2 controller chip scsi-1 reach 10mb/s indeed '' 20 % faster ide '' { 120 % 8.3 9.96 } . scsi facts posted newsgroup mac & ibm info sheet { available ftp sumex-aim.stanford.edu ( 36.44.0.6 ) info-mac/report mac-ibm-compare [ version # ] .txt ( 173 161 may still ) } part problem mac ibm pc inconsiant scsi . though well documented quadra scsi-2 chip apple salesperson said `` uses fast scsi-1 chip '' { 6mb/s , 10mb/s burst . scsi-1 5mb/s maximum synchronous quadra uses ansynchronous scsi slower } seems mac ibm see scsi-1 interface think 'scsi-1 ' maybe scsi-1 interface driven machine scsi-2 controller chip 8-bit mode { much faster true scsi-1 go } . n't slam article n't understand going . one reference quadra 's scsi-2 controller chip ( digital review , oct 21 , 1991 v8 n33 p8 ( 1 ) ) ."

In [41]:
text_line[0]

": lerxst @ wam.umd.edu ( 's thing ) subject : car ! ? nntp-posting-host : rac3.wam.umd.edu organization : university maryland , college park lines : 15 wondering anyone could enlighten car saw day . 2-door sports car , looked late 60s/ early 70s . called bricklin . doors really small . addition , front bumper separate rest body . know . anyone tellme model name , engine specs , years production , car made , history , whatever info funky looking car , please e-mail . thanks , - il -- -- brought neighborhood lerxst -- --"